import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PR-Market",
  description: "Generated by PR-Connect",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-f">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative h-full`}
      >
        <main className="relative flex flex-col min-h-screen">{children}</main>
      </body>
    </html>
  );
}
